// Comprehensive mock data for all dashboard types
// Used when Dev Settings > Mock Data is enabled

// ============= CONSUMER DASHBOARD DATA =============
export const mockConsumerOrders = [
  {
    id: "mock-order-1",
    order_number: "KWM-2024-001",
    consumer_id: "demo-consumer-001",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "preparing",
    subtotal: 85.50,
    shopper_fee: 12.00,
    total: 97.50,
    special_instructions: "Please select ripe tomatoes",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "i1", product_name: "Fresh Tomatoes", quantity: 3, unit_price: 15, total_price: 45, notes: "" },
      { id: "i2", product_name: "Garden Eggs", quantity: 2, unit_price: 8, total_price: 16, notes: "" },
      { id: "i3", product_name: "Shito (Hot Pepper)", quantity: 1, unit_price: 24.50, total_price: 24.50, notes: "" },
    ],
  },
  {
    id: "mock-order-2",
    order_number: "KWM-2024-002",
    consumer_id: "demo-consumer-001",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "completed",
    subtotal: 120.00,
    shopper_fee: 15.00,
    total: 135.00,
    special_instructions: "",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    items: [
      { id: "i4", product_name: "Fresh Tilapia", quantity: 2, unit_price: 45, total_price: 90, notes: "" },
      { id: "i5", product_name: "Palm Oil", quantity: 1, unit_price: 30, total_price: 30, notes: "" },
    ],
  },
  {
    id: "mock-order-3",
    order_number: "KWM-2024-003",
    consumer_id: "demo-consumer-001",
    vendor_id: "demo-vendor-002",
    market_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    status: "pending",
    subtotal: 45.00,
    shopper_fee: 10.00,
    total: 55.00,
    special_instructions: "Call when arriving",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "i6", product_name: "Kontomire Leaves", quantity: 3, unit_price: 5, total_price: 15, notes: "" },
      { id: "i7", product_name: "Onions", quantity: 2, unit_price: 15, total_price: 30, notes: "" },
    ],
  },
  {
    id: "mock-order-4",
    order_number: "KWM-2024-004",
    consumer_id: "demo-consumer-001",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "ready",
    subtotal: 200.00,
    shopper_fee: 20.00,
    total: 220.00,
    special_instructions: "",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "i8", product_name: "Beef (Steak Cut)", quantity: 2, unit_price: 80, total_price: 160, notes: "" },
      { id: "i9", product_name: "Ginger", quantity: 1, unit_price: 12, total_price: 12, notes: "" },
      { id: "i10", product_name: "Garlic", quantity: 1, unit_price: 18, total_price: 18, notes: "" },
      { id: "i11", product_name: "Pepper", quantity: 1, unit_price: 10, total_price: 10, notes: "" },
    ],
  },
  {
    id: "mock-order-5",
    order_number: "KWM-2024-005",
    consumer_id: "demo-consumer-001",
    vendor_id: "demo-vendor-003",
    market_id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    status: "disputed",
    subtotal: 65.00,
    shopper_fee: 12.00,
    total: 77.00,
    special_instructions: "Handle with care",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    items: [
      { id: "i12", product_name: "Eggs (Crate)", quantity: 1, unit_price: 65, total_price: 65, notes: "Some broken" },
    ],
  },
];

// ============= VENDOR DASHBOARD DATA =============
export const mockVendor = {
  id: "demo-vendor-001",
  user_id: "demo-vendor-001",
  business_name: "Auntie Akua's Fresh Produce",
  market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  description: "Fresh vegetables and fruits sourced daily from local farms. Quality guaranteed!",
  stall_number: "A-15",
  rating: 4.8,
  total_orders: 328,
  is_verified: true,
  is_active: true,
  created_at: new Date(Date.now() - 86400000 * 180).toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockVendorProducts = [
  {
    id: "vp1",
    vendor_id: "demo-vendor-001",
    name: "Fresh Tomatoes",
    description: "Locally grown, perfectly ripe tomatoes",
    price: 15.00,
    unit: "kg",
    category_id: "11111111-1111-1111-1111-111111111111",
    image_url: "https://images.unsplash.com/photo-1546470427-1d94d2abfc5b?w=400",
    is_available: true,
    stock_quantity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "vp2",
    vendor_id: "demo-vendor-001",
    name: "Garden Eggs",
    description: "Fresh garden eggs, perfect for stews",
    price: 8.00,
    unit: "bunch",
    category_id: "11111111-1111-1111-1111-111111111111",
    image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400",
    is_available: true,
    stock_quantity: 35,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "vp3",
    vendor_id: "demo-vendor-001",
    name: "Kontomire (Cocoyam Leaves)",
    description: "Fresh green kontomire leaves",
    price: 5.00,
    unit: "bunch",
    category_id: "11111111-1111-1111-1111-111111111111",
    image_url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
    is_available: true,
    stock_quantity: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "vp4",
    vendor_id: "demo-vendor-001",
    name: "Onions",
    description: "Large red onions",
    price: 15.00,
    unit: "kg",
    category_id: "11111111-1111-1111-1111-111111111111",
    image_url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400",
    is_available: true,
    stock_quantity: 45,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "vp5",
    vendor_id: "demo-vendor-001",
    name: "Peppers (Scotch Bonnet)",
    description: "Hot scotch bonnet peppers",
    price: 12.00,
    unit: "bag",
    category_id: "66666666-6666-6666-6666-666666666666",
    image_url: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400",
    is_available: false,
    stock_quantity: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockVendorOrders = [
  {
    id: "vo1",
    order_number: "KWM-2024-101",
    consumer_id: "c1",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "pending",
    subtotal: 67.00,
    shopper_fee: 10.00,
    total: 77.00,
    special_instructions: "Please pack separately",
    created_at: new Date(Date.now() - 600000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "vi1", product_name: "Fresh Tomatoes", quantity: 2, unit_price: 15, total_price: 30, notes: "" },
      { id: "vi2", product_name: "Garden Eggs", quantity: 2, unit_price: 8, total_price: 16, notes: "" },
      { id: "vi3", product_name: "Kontomire", quantity: 3, unit_price: 5, total_price: 15, notes: "" },
      { id: "vi4", product_name: "Ginger", quantity: 0.5, unit_price: 12, total_price: 6, notes: "" },
    ],
  },
  {
    id: "vo2",
    order_number: "KWM-2024-102",
    consumer_id: "c2",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "accepted",
    subtotal: 95.00,
    shopper_fee: 12.00,
    total: 107.00,
    special_instructions: "",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "vi5", product_name: "Onions", quantity: 3, unit_price: 15, total_price: 45, notes: "" },
      { id: "vi6", product_name: "Fresh Tomatoes", quantity: 2, unit_price: 15, total_price: 30, notes: "" },
      { id: "vi7", product_name: "Garden Eggs", quantity: 2.5, unit_price: 8, total_price: 20, notes: "" },
    ],
  },
  {
    id: "vo3",
    order_number: "KWM-2024-103",
    consumer_id: "c3",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "preparing",
    subtotal: 42.00,
    shopper_fee: 10.00,
    total: 52.00,
    special_instructions: "Rush order please",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "vi8", product_name: "Fresh Tomatoes", quantity: 1.5, unit_price: 15, total_price: 22.50, notes: "" },
      { id: "vi9", product_name: "Kontomire", quantity: 2, unit_price: 5, total_price: 10, notes: "" },
      { id: "vi10", product_name: "Garden Eggs", quantity: 1, unit_price: 8, total_price: 8, notes: "" },
    ],
  },
  {
    id: "vo4",
    order_number: "KWM-2024-099",
    consumer_id: "c4",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "ready",
    subtotal: 120.00,
    shopper_fee: 15.00,
    total: 135.00,
    special_instructions: "",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      { id: "vi11", product_name: "Onions", quantity: 5, unit_price: 15, total_price: 75, notes: "" },
      { id: "vi12", product_name: "Fresh Tomatoes", quantity: 3, unit_price: 15, total_price: 45, notes: "" },
    ],
  },
  {
    id: "vo5",
    order_number: "KWM-2024-088",
    consumer_id: "c5",
    vendor_id: "demo-vendor-001",
    market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "completed",
    subtotal: 85.00,
    shopper_fee: 12.00,
    total: 97.00,
    special_instructions: "",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 82800000).toISOString(),
    items: [
      { id: "vi13", product_name: "Mixed Vegetables", quantity: 1, unit_price: 85, total_price: 85, notes: "" },
    ],
  },
];

// ============= SHOPPER DASHBOARD DATA =============
export const mockShopper = {
  id: "demo-shopper-001",
  user_id: "demo-shopper-001",
  market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  is_available: true,
  is_verified: true,
  rating: 4.9,
  total_deliveries: 156,
  commission_rate: 0.15,
  created_at: new Date(Date.now() - 86400000 * 90).toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockAvailableJobs = [
  {
    id: "job1",
    order_id: "o1",
    shopper_id: null,
    status: "pending",
    commission_amount: 15.00,
    created_at: new Date(Date.now() - 300000).toISOString(),
    accepted_at: null,
    picked_up_at: null,
    delivered_at: null,
    order: {
      id: "o1",
      order_number: "KWM-2024-201",
      market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      total: 97.50,
      status: "ready",
      special_instructions: "Call on arrival",
      items: [
        { product_name: "Fresh Tomatoes", quantity: 3 },
        { product_name: "Garden Eggs", quantity: 2 },
        { product_name: "Shito", quantity: 1 },
      ],
    },
  },
  {
    id: "job2",
    order_id: "o2",
    shopper_id: null,
    status: "pending",
    commission_amount: 18.00,
    created_at: new Date(Date.now() - 600000).toISOString(),
    accepted_at: null,
    picked_up_at: null,
    delivered_at: null,
    order: {
      id: "o2",
      order_number: "KWM-2024-202",
      market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      total: 120.00,
      status: "ready",
      special_instructions: "",
      items: [
        { product_name: "Fresh Tilapia", quantity: 2 },
        { product_name: "Palm Oil", quantity: 1 },
      ],
    },
  },
  {
    id: "job3",
    order_id: "o3",
    shopper_id: null,
    status: "pending",
    commission_amount: 22.00,
    created_at: new Date(Date.now() - 900000).toISOString(),
    accepted_at: null,
    picked_up_at: null,
    delivered_at: null,
    order: {
      id: "o3",
      order_number: "KWM-2024-203",
      market_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      total: 150.00,
      status: "ready",
      special_instructions: "Large order - multiple bags",
      items: [
        { product_name: "Beef", quantity: 2 },
        { product_name: "Onions", quantity: 3 },
        { product_name: "Tomatoes", quantity: 2 },
        { product_name: "Peppers", quantity: 1 },
      ],
    },
  },
];

export const mockActiveJobs = [
  {
    id: "job4",
    order_id: "o4",
    shopper_id: "demo-shopper-001",
    status: "accepted",
    commission_amount: 12.00,
    created_at: new Date(Date.now() - 1800000).toISOString(),
    accepted_at: new Date(Date.now() - 1200000).toISOString(),
    picked_up_at: null,
    delivered_at: null,
    order: {
      id: "o4",
      order_number: "KWM-2024-199",
      market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      total: 80.00,
      status: "ready",
      special_instructions: "Fragile items",
      items: [
        { product_name: "Eggs (Crate)", quantity: 1 },
        { product_name: "Milk", quantity: 2 },
      ],
    },
  },
];

export const mockCompletedJobs = [
  {
    id: "job5",
    order_id: "o5",
    shopper_id: "demo-shopper-001",
    status: "completed",
    commission_amount: 15.00,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    accepted_at: new Date(Date.now() - 86400000 + 600000).toISOString(),
    picked_up_at: new Date(Date.now() - 86400000 + 1800000).toISOString(),
    delivered_at: new Date(Date.now() - 86400000 + 3600000).toISOString(),
    order: {
      id: "o5",
      order_number: "KWM-2024-180",
      market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      total: 100.00,
      status: "completed",
    },
  },
  {
    id: "job6",
    order_id: "o6",
    shopper_id: "demo-shopper-001",
    status: "completed",
    commission_amount: 20.00,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    accepted_at: new Date(Date.now() - 86400000 * 2 + 300000).toISOString(),
    picked_up_at: new Date(Date.now() - 86400000 * 2 + 1200000).toISOString(),
    delivered_at: new Date(Date.now() - 86400000 * 2 + 2400000).toISOString(),
    order: {
      id: "o6",
      order_number: "KWM-2024-175",
      market_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      total: 135.00,
      status: "completed",
    },
  },
];

// ============= ADMIN DASHBOARD DATA =============
export const mockAdminStats = {
  totalUsers: 1245,
  totalVendors: 89,
  totalShoppers: 45,
  totalOrders: 3567,
  todayOrders: 47,
  pendingDisputes: 3,
  pendingVerifications: 12,
  totalRevenue: 156780.50,
  todayRevenue: 2450.00,
};

export const mockAdminOrders = [
  ...mockConsumerOrders,
  ...mockVendorOrders.map(o => ({ ...o, id: `admin-${o.id}` })),
];

export const mockAdminUsers = [
  {
    id: "u1",
    email: "consumer1@kwikmarket.dev",
    full_name: "Kofi Mensah",
    role: "consumer",
    is_verified: true,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "u2",
    email: "vendor1@kwikmarket.dev",
    full_name: "Akua Boateng",
    role: "vendor",
    is_verified: true,
    created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: "u3",
    email: "shopper1@kwikmarket.dev",
    full_name: "Kwame Asante",
    role: "shopper",
    is_verified: true,
    created_at: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    id: "u4",
    email: "pending.vendor@kwikmarket.dev",
    full_name: "Ama Darko",
    role: "vendor",
    is_verified: false,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "u5",
    email: "pending.shopper@kwikmarket.dev",
    full_name: "Yaw Owusu",
    role: "shopper",
    is_verified: false,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockDisputes = [
  {
    id: "d1",
    order_id: "mock-order-5",
    order_number: "KWM-2024-005",
    consumer_name: "Demo Consumer",
    vendor_name: "Kwaku's Eggs",
    reason: "Items damaged on delivery - broken eggs",
    status: "pending",
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "d2",
    order_id: "d-order-2",
    order_number: "KWM-2024-156",
    consumer_name: "Esi Mensah",
    vendor_name: "Fresh Fish Corner",
    reason: "Wrong items delivered",
    status: "investigating",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "d3",
    order_id: "d-order-3",
    order_number: "KWM-2024-142",
    consumer_name: "Kwabena Adu",
    vendor_name: "Auntie Akua's Fresh Produce",
    reason: "Late delivery - items spoiled",
    status: "resolved",
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];
